### ISSUE TITLE
Sound effect delay when timer hits 0

### ISSUE THREAD

**Issue by gwgorman** [FirstLegoLeague/tournament#101]
It seemed to us during the past 2 weeks of tournament use that the clock has to hit "-1" for the ending buzzer to sound. Either that our our PC is super slow at playing sounds...we would have expected the buzzer to sound as soon as 0:00 is displayed, but it appeared to us to be about 1 second *after* 0:00... ?? anyone else see this?

**Comment by gwgorman** [comment]
Closing..seems to be fixed in 2019 update!

**Comment by alanggreen** [comment]
The sound generation has been reworked. The browser generates the sounds
instead of the server. That means less delay, and also allows you to have a
second computer closer to the sound system, and to connect that I've to the
amplifier
